
import javax.swing.ButtonGroup;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nacho
 */
public class vehiculosJFrame extends javax.swing.JFrame {
    ButtonGroup nombre=new ButtonGroup();

    /**
     * Creates new form vehiculosJFrame
     */
    public vehiculosJFrame() {
        initComponents();
        nombre.add(chkCamion);
        nombre.add(chkCoche);
        nombre.add(chkMoto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        chkCoche = new javax.swing.JCheckBox();
        chkMoto = new javax.swing.JCheckBox();
        chkCamion = new javax.swing.JCheckBox();
        chkSidecar = new javax.swing.JCheckBox();
        chkCapota = new javax.swing.JCheckBox();
        chkRemolque = new javax.swing.JCheckBox();
        btnReset = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        comboColors = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMarca.setText("Marca");

        lblModelo.setText("Modelo");

        chkCoche.setText("coche");
        chkCoche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkCocheMouseClicked(evt);
            }
        });

        chkMoto.setText("moto");
        chkMoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkMotoMouseClicked(evt);
            }
        });

        chkCamion.setText("camion");
        chkCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkCamionMouseClicked(evt);
            }
        });

        chkSidecar.setText("sidecar");

        chkCapota.setText("capota");

        chkRemolque.setText("remolque");

        btnReset.setText("reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });

        btnResult.setText("result");
        btnResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResultMouseClicked(evt);
            }
        });

        comboColors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "colors", "rojo", "azul", "amarillo verde", " " }));
        comboColors.setToolTipText("");
        comboColors.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblModelo)
                            .addComponent(lblMarca))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtModelo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReset)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkCoche)
                                .addComponent(chkMoto)
                                .addComponent(chkCamion)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkRemolque)
                            .addComponent(chkCapota)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkSidecar)
                                .addGap(61, 61, 61)
                                .addComponent(comboColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnResult))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCoche)
                    .addComponent(chkSidecar)
                    .addComponent(comboColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMoto)
                    .addComponent(chkCapota))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCamion)
                    .addComponent(chkRemolque))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnResult))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkCocheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkCocheMouseClicked
        // TODO add your handling code here:
        chkCapota.setEnabled(true);
        chkRemolque.setEnabled(true);
        chkSidecar.setEnabled(false);
        chkMoto.setSelected(false);
        chkCamion.setSelected(false);
        chkSidecar.setSelected(false);
    }//GEN-LAST:event_chkCocheMouseClicked

    private void chkMotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkMotoMouseClicked
        // TODO add your handling code here:
        chkSidecar.setEnabled(true);
        chkCapota.setEnabled(false);
        chkRemolque.setEnabled(false);
        chkCoche.setSelected(false);
        chkCamion.setSelected(false);
    }//GEN-LAST:event_chkMotoMouseClicked

    private void chkCamionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkCamionMouseClicked
        // TODO add your handling code here:
        chkCapota.setEnabled(true);
        chkRemolque.setEnabled(true);
        chkSidecar.setEnabled(false);
        chkCoche.setSelected(false);
        chkMoto.setSelected(false);
        chkSidecar.setSelected(false);
    }//GEN-LAST:event_chkCamionMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        
        chkRemolque.setSelected(false);
        chkSidecar.setSelected(false);
        chkCapota.setSelected(false);
        txtModelo.setText(null);
        txtMarca.setText(null);
        chkRemolque.setEnabled(true);
        chkCapota.setEnabled(true);
        chkSidecar.setEnabled(true);
        nombre.clearSelection();
        
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultMouseClicked
        // TODO add your handling code here:
        javax.swing.JCheckBox[] tipoComplemento={chkSidecar,chkRemolque, chkCapota};
        javax.swing.JCheckBox[] tipoVehiculo={chkCoche,chkCamion, chkMoto};
        System.out.println("tu vehiculo es ");
        for(javax.swing.JCheckBox vehiculo:tipoVehiculo){ 
            if(vehiculo.isSelected()){System.out.println(vehiculo.getText());}
        }
        System.out.println(comboColors.getSelectedItem());    
        
        System.out.println("tienes los siguientes complementos ");
        
        for(javax.swing.JCheckBox complemento:tipoComplemento){ 
            if(complemento.isSelected()){System.out.println(complemento.getText());}
        }
    }//GEN-LAST:event_btnResultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehiculosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehiculosJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResult;
    private javax.swing.JCheckBox chkCamion;
    private javax.swing.JCheckBox chkCapota;
    private javax.swing.JCheckBox chkCoche;
    private javax.swing.JCheckBox chkMoto;
    private javax.swing.JCheckBox chkRemolque;
    private javax.swing.JCheckBox chkSidecar;
    private javax.swing.JComboBox<String> comboColors;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
